/**
 * Counties of England, UK
 *
 * Includes current and historical (and County borough)
 *
 * @see https://en.wikipedia.org/wiki/List_of_counties_of_the_United_Kingdom#England
 * @see https://en.wikipedia.org/wiki/County_borough
 */
const EnglishCounties:Array<string> = [
  'avon',
  'barnsley',
  'barrow-in-furness',
  'bath',
  'bedford',
  'bedforshire',
  'berkshire',
  'birkenhead',
  'birmingham',
  'blackburn',
  'blackpool',
  'bolton',
  'bootle',
  'bournemouth',
  'bradford',
  'brighton',
  'bristol',
  'buckinghamshire',
  'burnley',
  'burton',
  'bury',
  'cambridgeshire',
  'canterbury',
  'cardiff',
  'carlisle',
  'central bedfordshire',
  'chesire east',
  'chesire west',
  'chesire',
  'chester',
  'christchurch',
  'cleveland',
  'cornwall',
  'coventry',
  'cumberland',
  'cumbria',
  'darlington',
  'darwen',
  'derby',
  'derbyshire',
  'devon',
  'dewsbury',
  'doncaster',
  'dorset',
  'dudley',
  'durham',
  'east riding',
  'east suffolk',
  'east sussex',
  'eastbourne',
  'essex',
  'exeter',
  'gateshead',
  'gloucester',
  'gloucestershire',
  'greater london',
  'greater manchester',
  'grimsby',
  'halifax',
  'halton',
  'hampshire',
  'hartlepool',
  'hastings',
  'hereford',
  'herefordshire',
  'hertfordshire',
  'hove',
  'huddersfield',
  'hull',
  'humbershide',
  'huntingdon',
  'huntingdonshire',
  'ipswich',
  'isle of ely',
  'isle of wight',
  'kent',
  'kingston',
  'lancashire',
  'leeds',
  'leicester',
  'leichestershire',
  'lincoln',
  'lincolnshire',
  'liverpool',
  'london',
  'luton',
  'manchester',
  'medway',
  'merseyside',
  'middlesbrough',
  'middlesex',
  'milton keynes',
  'newcastle upon tyne',
  'newport',
  'norfolk',
  'north east lincolnshire',
  'north east somerset',
  'north humberside',
  'north lincolnshire',
  'north northamptonshire',
  'north riding',
  'north somerset',
  'north yorkshire',
  'northampton',
  'northamptonshire',
  'northumberland',
  'norwich',
  'nottingham',
  'nottinghamshire',
  'oldham',
  'oxford',
  'oxfordshire',
  'peterborough',
  'plymouth',
  'poole',
  'portsmouth',
  'preston',
  'reading',
  'redcar and cleveland',
  'redcar',
  'rochdale',
  'rotherham',
  'rutland',
  'salford',
  'sheffield',
  'shropshire',
  'soke of peterborough',
  'solihull',
  'somerset',
  'south gloucestershire',
  'south humberside',
  'south shields',
  'south yorkshire',
  'southampton',
  'southend-on-sea',
  'southport',
  'st helens',
  'staffordshire',
  'stockport',
  'stockton-on-tees',
  'stoke on trent',
  'stoke-on-trent',
  'suffolk',
  'sunderland',
  'surrey',
  'sussex',
  'swansea',
  'swindon',
  'teesside',
  'telford',
  'thurrock',
  'torbay',
  'tyne',
  'tynemouth',
  'wakefield',
  'wallasey',
  'walsall',
  'warley',
  'warrickshire',
  'warrington',
  'warwickshire',
  'wear',
  'west bromwich',
  'west midlands',
  'west northamptonshire',
  'west riding',
  'west suffolk',
  'west sussex',
  'west yorkshire',
  'westmorland',
  'wigan',
  'wiltshire',
  'wolverhampton',
  'worcester',
  'worcestershire',
  'wrekin',
  'yarmouth',
  'york',
  'yorkshire',
]
export default EnglishCounties
